#!/usr/bin/env php
<?php

if ('cli' !== php_sapi_name()) {
    printf("Error: This script must be run on CLI only\n");
    exit(1);
}

if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    printf("Error: composer autoload missing\n");
    printf("Please run \"ctrl.sh install\" before running this application\n");
    exit(1);
}

require(__DIR__ . '/vendor/autoload.php');

$application = new \Symfony\Component\Console\Application();
$application->add(new \VerteXVaaR\Front\Command\FrontCommand());
$application->setDefaultCommand(\VerteXVaaR\Front\Command\FrontCommand::getDefaultName());
$application->run();
